{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx           # ingress controller
  rules:
  - http:
      paths:
      - path: /           
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-userapp-service
            port:
              number: {{ .Values.userApp.service.port }}
{{- end }}
