apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: retail-app-ingress
  namespace: subbu-1-ns
spec:
  ingressClassName: nginx           # ingress controller
  rules:
  - http:
      paths:
      - path: /           
        pathType: Prefix
        backend:
          service:
            name: usernode-js-service
            port:
              number: 3130
